Interface/app/main/log/__init__.py
from flask import Blueprint

log = Blueprint('log', __name__, url_prefix='/logs_info', template_folder='templates')
from . import views

Interface/app/main/log/views.py
from app import db
from app.models import Book, Log, Permission, Temperature, Residents, Visitors
from flask import render_template, url_for, flash, redirect, request, abort
from flask_login import login_required, current_user
from . import log
from ..decorators import permission_required


@log.route('/borrow/')
@login_required
@permission_required(Permission.BORROW_BOOK)
def book_borrow():
    book_id = request.args.get('book_id')
    the_book = Book.query.get_or_404(book_id)
    if the_book.hidden and not current_user.is_administrator():
        abort(404)

    result, message = current_user.borrow_book(the_book)
    flash(message, 'success' if result else 'danger')
    db.session.commit()
    return redirect(request.args.get('next') or url_for('book.detail', book_id=book_id))


@log.route('/return/')
@login_required
@permission_required(Permission.RETURN_BOOK)
def book_return():
    log_id = request.args.get('log_id')
    book_id = request.args.get('book_id')
    the_log = None
    if log_id:
        the_log = Log.query.get(log_id)
    if book_id:
        the_log = Log.query.filter_by(user_id=current_user.id, book_id=book_id).first()
    if log is None:
        flash(u'没有找到这条记录', 'warning')
    else:
        result, message = current_user.return_book(the_log)
        flash(message, 'success' if result else 'danger')
        db.session.commit()
    return redirect(request.args.get('next') or url_for('book.detail', book_id=log_id))


@log.route('/')
@login_required
def index():
    show = request.args.get('show', 0, type=int)
    if show != 0:
        show = 1

    page = request.args.get('page', 1, type=int)
    #pagination = Log.query.filter_by(returned=show).order_by(Log.borrow_timestamp.desc()).paginate(page, per_page=10)
    
    query = db.session().query(Temperature, Residents)
    query = query.join(Temperature, Temperature.id_number==Residents.id_number)
    pagination = query.order_by(Temperature.record_timestamp.desc()).paginate(page, per_page=10)

    #pagination = Temperature.query.order_by(Temperature.record_timestamp.desc()).paginate(page, per_page=10)
    #pagination = data
    logs0 = pagination.items

    query = db.session().query(Temperature, Visitors)
    query = query.join(Temperature, Temperature.id_number==Visitors.id_number)
    pagination = query.order_by(Temperature.record_timestamp.desc()).paginate(page, per_page=10)

    logs1 = pagination.items
    return render_template("logs_info.html", logs0=logs0, logs1=logs1, pagination=pagination, title=u"借阅信息")

Interface/app/main/log/templates/logs_info.html
{% extends "base.html" %}
{% from "bootstrap/pagination.html" import render_pagination %}
{% block mycontent %}
    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
        {% if request.args.get('show',0)!='1' %}
            <li role="presentation" class="active"><a href="#" role="tab">小区居民</a></li>
            <li role="presentation"><a href="{{ url_for('log.index',show=1) }}" role="tab">外来人员</a></li>
        {% else %}
            <li role="presentation"><a href="{{ url_for('log.index',show=0) }}" role="tab">小区居民</a></li>
            <li role="presentation" class="active"><a href="#" role="tab">外来人员</a></li>
        {% endif %}
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
        {% if request.args.get('show',0)!='1' %}
            <table class="table table-striped table-hover">
                <thead class="hidden-xs">
                <tr>
                    <th>姓名</th>
                    <th>证件类型</th>
                    <th>证件号码</th>
                    <th>体温(℃)</th>
                    <th>测量时间</th>
                    <th>测量地点</th>
                    <th>手机号码</th>
                    {%- if current_user.is_authenticated -%}
                        <th>体温情况</th>
                    {%- endif -%}
                </tr>
                </thead>
                <tbody>
                {% for log in logs0 %}
                    <tr class="animated fadeIn delay-{{ loop.index0 }}">
                        {% if log[0].isresident == True %}
                            <td><a href="{{ url_for('book.people_detail',people_id=log[1].id_number,isresident=log[0].isresident) }}">{{ log[1].name }}</a></td>
                            <td class="hidden-xs">{{ log[1].id_type }}</td>
                            <td class="hidden-xs">{{ log[1].id_number }}</td>
                            <td class="hidden-xs">{{ log[0].temperature }}</td>
                            <td class="hidden-xs">{{ log[0].record_timestamp.strftime('%d %B %Y - %H:%M:%S') }}</td>
                            <td class="hidden-xs">{{ log[0].gate_number }}</td>
                            <td class="hidden-xs">{{ log[1].phone_number }}</td>
                            {%- if current_user.is_authenticated -%}
                                <td class="hidden-xs">
                                    {% if log[0].temperature < 37.3 %}
                                        <button class="btn btn-success btn-block" disabled>正常</button>
                                    {% else %}
                                        <button class="btn btn-danger btn-block" disabled>异常</button>
                                    {% endif %}
                            {%- endif -%}
                            </td>
                        </tr>
                        {% endif %}
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            {% if request.args.get('show',0) =='1' %}
            <table class="table table-striped table-hover">
                <thead class="hidden-xs">
                <tr>
                    <th>姓名</th>
                    <th>证件类型</th>
                    <th>证件号码</th>
                    <th>体温(℃)</th>
                    <th>测量时间</th>
                    <th>测量地点</th>
                    <th>手机号码</th>
                    {%- if current_user.is_authenticated -%}
                        <th>体温情况</th>
                    {%- endif -%}
                </tr>
                </thead>
                <tbody>
                {% for log in logs1 %}
                    <tr class="animated fadeIn delay-{{ loop.index0 }}">
                        {% if log[0].isresident == False %}
                            <td><a href="{{ url_for('book.people_detail',people_id=log[1].id_number,isresident=log[0].isresident) }}"> {{ log[1].name }}</a></td>
                            <td class="hidden-xs">{{ log[1].id_type }}</td>
                            <td class="hidden-xs">{{ log[1].id_number }}</td>
                            <td class="hidden-xs">{{ log[0].temperature }}</td>
                            <td class="hidden-xs">{{ log[0].record_timestamp.strftime('%d %B %Y - %H:%M:%S') }}</td>
                            <td class="hidden-xs">{{ log[0].gate_number }}</td>
                            <td class="hidden-xs">{{ log[1].phone_number }}</td>
                            {%- if current_user.is_authenticated -%}
                                <td class="hidden-xs">
                                    {% if log[0].temperature < 37.3 %}
                                        <button class="btn btn-success btn-block" disabled>正常</button>
                                    {% else %}
                                        <button class="btn btn-danger btn-block" disabled>异常</button>
                                    {% endif %}
                            {%- endif -%}
                            </td>
                    </tr>
                        {% endif %}
                {% endfor %}
                </tbody>
            </table>
            {% endif %}
        {% endif %}
    {% if pagination and pagination.pages > 1 %}
        <div class="container-fluid text-center">
            {{ render_pagination(pagination) }}
        </div>
    {% endif %}
{% endblock %}